import { JsonUIElement } from "../jsonUI/JsonUIElement"
import { Anchor } from "./Anchor"
import { ClipDirection } from "./ClipDirecion"
import { Collection } from "./Collection"
import { Direction } from "./Direction"
import { FocusContainerCustom } from "./FocusContainerCustom"
import { FocusNavigationMode } from "./FocusNavigationMode"
import { FontSize } from "./FontSize"
import { FontType } from "./FontType"
import { ArrayProperty } from "./LanguageInterface"
import { Orientation } from "./Orientation"
import { PropertyBagKey } from "./PropertyBagKeys"
import { Renderer } from "./Renderer"
import { RotationAuto } from "./RotationAuto"
import { SoundObject } from "./SoundObject"
import { TextType } from "./TextTypes"
import { TextureFileSystem } from "./TextureFileSystem"
import { Bool, Num, Vector2, Obj, Vector2_str, Vector3, ArrString, Vector4 } from "./Types"

export interface JsonUIProperty {
    visible?: string | JsonUIElement | ArrayProperty | Bool,
    enabled?: string | JsonUIElement | ArrayProperty | Bool,
    layer?: string | JsonUIElement | ArrayProperty | Num,
    alpha?: string | JsonUIElement | ArrayProperty | Num,
    propagate_alpha?: string | JsonUIElement | ArrayProperty | Bool,
    clips_children?: string | JsonUIElement | ArrayProperty | Bool,
    allow_clipping?: string | JsonUIElement | ArrayProperty | Bool,
    clip_offset?: string | JsonUIElement | ArrayProperty | Vector2,
    clip_state_change_event?: string | JsonUIElement | ArrayProperty,
    enable_scissor_test?: string | JsonUIElement | ArrayProperty | Bool,
    property_bag?: string | JsonUIElement | ArrayProperty | Obj | {
        [key in PropertyBagKey]: any
    },
    selected?: string | JsonUIElement | ArrayProperty | Bool,
    use_child_anchors?: string | JsonUIElement | ArrayProperty | Bool,
    disable_anim_fast_forward?: string | JsonUIElement | ArrayProperty | Bool,
    animation_reset_name?: string | JsonUIElement | ArrayProperty,
    ignored?: string | JsonUIElement | ArrayProperty | Bool,
    grid_position?: string | JsonUIElement | ArrayProperty | Vector2,
    collection_index?: string | JsonUIElement | ArrayProperty | Num,
    size?: string | JsonUIElement | ArrayProperty | Vector2_str,
    max_size?: string | JsonUIElement | ArrayProperty | Vector2_str,
    min_size?: string | JsonUIElement | ArrayProperty | Vector2_str,
    offset?: string | JsonUIElement | ArrayProperty | Vector2_str,
    anchor?: string | JsonUIElement | ArrayProperty | Anchor,
    anchor_from?: string | JsonUIElement | ArrayProperty | Anchor,
    anchor_to?: string | JsonUIElement | ArrayProperty | Anchor,
    inherit_max_sibling_width?: string | JsonUIElement | ArrayProperty | Bool,
    inherit_max_sibling_height?: string | JsonUIElement | ArrayProperty | Bool,
    use_anchored_offset?: string | JsonUIElement | ArrayProperty | Bool,
    contained?: string | JsonUIElement | ArrayProperty | Bool,
    draggable?: string | JsonUIElement | ArrayProperty | Direction,
    follows_cursor?: string | JsonUIElement | ArrayProperty | Bool,
    grid_dimensions?: string | JsonUIElement | ArrayProperty | Vector2,
    maximum_grid_items?: string | JsonUIElement | ArrayProperty | Num,
    grid_dimension_binding?: string | JsonUIElement | ArrayProperty,
    grid_rescaling_type?: string | JsonUIElement | ArrayProperty | Direction,
    grid_fill_direction?: string | JsonUIElement | ArrayProperty | Direction,
    grid_item_template?: string | JsonUIElement | ArrayProperty,
    precached_grid_item_count?: string | JsonUIElement | ArrayProperty | Num,
    text?: string | JsonUIElement | ArrayProperty,
    color?: string | JsonUIElement | ArrayProperty | Vector3,
    locked_color?: string | JsonUIElement | ArrayProperty | Vector3,
    shadow?: string | JsonUIElement | ArrayProperty | Bool,
    hide_hyphen?: string | JsonUIElement | ArrayProperty | Bool,
    notify_on_ellipses?: string | JsonUIElement | ArrayProperty | ArrString,
    enable_profanity_filter?: string | JsonUIElement | ArrayProperty | Bool,
    locked_alpha?: string | JsonUIElement | ArrayProperty | Num,
    font_scale_factor?: string | JsonUIElement | ArrayProperty | Num,
    localize?: string | JsonUIElement | ArrayProperty | Bool,
    line_padding?: string | JsonUIElement | ArrayProperty | Num,
    font_size?: string | JsonUIElement | ArrayProperty | FontSize,
    backup_font_type?: string | JsonUIElement | ArrayProperty | FontType,
    text_alignment?: string | JsonUIElement | ArrayProperty | Anchor,
    texture?: string | JsonUIElement | ArrayProperty,
    allow_debug_missing_texture?: string | JsonUIElement | ArrayProperty | Bool,
    uv?: string | JsonUIElement | ArrayProperty | Vector2,
    uv_size?: string | JsonUIElement | ArrayProperty | Vector2,
    texture_file_system?: string | JsonUIElement | ArrayProperty | TextureFileSystem,
    nineslice_size?: string | JsonUIElement | ArrayProperty | Vector2 | Vector4 | Num,
    tiled?: string | JsonUIElement | ArrayProperty | Bool | Vector2,
    tiled_scale?: string | JsonUIElement | ArrayProperty | Vector2,
    clip_direction?: string | JsonUIElement | ArrayProperty | ClipDirection,
    clip_ratio?: string | JsonUIElement | ArrayProperty | Num,
    clip_pixelperfect?: string | JsonUIElement | ArrayProperty | Bool,
    keep_ratio?: string | JsonUIElement | ArrayProperty | Bool,
    bilinear?: string | JsonUIElement | ArrayProperty | Bool,
    fill?: string | JsonUIElement | ArrayProperty | Bool,
    "$fit_to_width"?: string | JsonUIElement | ArrayProperty | Bool,
    zip_folder?: string | JsonUIElement | ArrayProperty,
    grayscale?: string | JsonUIElement | ArrayProperty | Bool,
    force_texture_reload?: string | JsonUIElement | ArrayProperty | Bool,
    base_size?: string | JsonUIElement | ArrayProperty | Vector2,
    modal?: string | JsonUIElement | ArrayProperty | Bool,
    inline_modal?: string | JsonUIElement | ArrayProperty | Bool,
    always_listen_to_input?: string | JsonUIElement | ArrayProperty | Bool,
    always_handle_pointer?: string | JsonUIElement | ArrayProperty | Bool,
    always_handle_controller_direction?: string | JsonUIElement | ArrayProperty | Bool,
    hover_enabled?: string | JsonUIElement | ArrayProperty | Bool,
    prevent_touch_input?: string | JsonUIElement | ArrayProperty | Bool,
    consume_event?: string | JsonUIElement | ArrayProperty | Bool,
    consume_hover_events?: string | JsonUIElement | ArrayProperty | Bool,
    gesture_tracking_button?: string | JsonUIElement | ArrayProperty | Bool,
    default_focus_precedence?: string | JsonUIElement | ArrayProperty | Num,
    focus_enabled?: string | JsonUIElement | ArrayProperty | Bool,
    focus_wrap_enabled?: string | JsonUIElement | ArrayProperty | Bool,
    focus_magnet_enabled?: string | JsonUIElement | ArrayProperty | Bool,
    focus_identifier?: string | JsonUIElement | ArrayProperty,
    focus_change_down?: string | JsonUIElement | ArrayProperty,
    focus_change_up?: string | JsonUIElement | ArrayProperty,
    focus_change_left?: string | JsonUIElement | ArrayProperty,
    focus_change_right?: string | JsonUIElement | ArrayProperty,
    focus_mapping?: string | JsonUIElement | ArrayProperty | any[],
    focus_container?: string | JsonUIElement | ArrayProperty | Bool,
    use_last_focus?: string | JsonUIElement | ArrayProperty | Bool,
    focus_navigation_mode_left?: string | JsonUIElement | ArrayProperty | FocusNavigationMode,
    focus_navigation_mode_right?: string | JsonUIElement | ArrayProperty | FocusNavigationMode,
    focus_navigation_mode_down?: string | JsonUIElement | ArrayProperty | FocusNavigationMode,
    focus_navigation_mode_up?: string | JsonUIElement | ArrayProperty | FocusNavigationMode,
    focus_container_custom_left?: string | JsonUIElement | ArrayProperty | FocusContainerCustom[],
    focus_container_custom_right?: string | JsonUIElement | ArrayProperty | FocusContainerCustom[],
    focus_container_custom_down?: string | JsonUIElement | ArrayProperty | FocusContainerCustom[],
    focus_container_custom_up?: string | JsonUIElement | ArrayProperty | FocusContainerCustom[],
    default_control?: string | JsonUIElement | ArrayProperty,
    hover_control?: string | JsonUIElement | ArrayProperty,
    pressed_control?: string | JsonUIElement | ArrayProperty,
    locked_control?: string | JsonUIElement | ArrayProperty,
    radio_toggle_group?: string | JsonUIElement | ArrayProperty | Bool,
    toggle_name?: string | JsonUIElement | ArrayProperty,
    toggle_default_state?: string | JsonUIElement | ArrayProperty | Bool,
    toggle_group_forced_index?: string | JsonUIElement | ArrayProperty | Num,
    toggle_group_default_selected?: string | JsonUIElement | ArrayProperty | Num,
    reset_on_focus_lost?: string | JsonUIElement | ArrayProperty | Bool,
    toggle_on_hover?: string | JsonUIElement | ArrayProperty,
    toggle_on_button?: string | JsonUIElement | ArrayProperty,
    toggle_off_button?: string | JsonUIElement | ArrayProperty,
    enable_directional_toggling?: string | JsonUIElement | ArrayProperty | Bool,
    toggle_grid_collection_name?: string | JsonUIElement | ArrayProperty,
    unchecked_control?: string | JsonUIElement | ArrayProperty,
    checked_control?: string | JsonUIElement | ArrayProperty,
    unchecked_hover_control?: string | JsonUIElement | ArrayProperty
    checked_hover_control?: string | JsonUIElement | ArrayProperty
    unchecked_locked_control?: string | JsonUIElement | ArrayProperty,
    checked_locked_control?: string | JsonUIElement | ArrayProperty,
    unchecked_locked_hover_control?: string | JsonUIElement | ArrayProperty,
    checked_locked_hover_control?: string | JsonUIElement | ArrayProperty,
    dropdown_name?: string | JsonUIElement | ArrayProperty,
    dropdown_content_control?: string | JsonUIElement | ArrayProperty,
    dropdown_area?: string | JsonUIElement | ArrayProperty,
    sound_name?: string | JsonUIElement | ArrayProperty,
    sound_volume?: string | JsonUIElement | ArrayProperty | Num,
    sound_pitch?: string | JsonUIElement | ArrayProperty | Num,
    sounds?: string | JsonUIElement | ArrayProperty | SoundObject[],
    collection?: string | JsonUIElement | ArrayProperty | Collection,
    collection_name?: string | JsonUIElement | ArrayProperty | Collection,
    text_box_name?: string | JsonUIElement | ArrayProperty,
    text_edit_box_grid_collection_name?: string | JsonUIElement | ArrayProperty,
    constrain_to_rect?: string | JsonUIElement | ArrayProperty | Bool,
    enabled_newline?: string | JsonUIElement | ArrayProperty | Bool,
    text_type?: string | JsonUIElement | ArrayProperty | TextType,
    max_length?: string | JsonUIElement | ArrayProperty | Num,
    text_control?: string | JsonUIElement | ArrayProperty,
    place_holder_control?: string | JsonUIElement | ArrayProperty,
    can_be_deselected?: string | JsonUIElement | ArrayProperty | Bool,
    always_listening?: string | JsonUIElement | ArrayProperty | Bool,
    virtual_keyboard_buffer_control?: string | JsonUIElement | ArrayProperty,
    slider_track_button?: string | JsonUIElement | ArrayProperty,
    slider_small_decrease_button?: string | JsonUIElement | ArrayProperty,
    slider_small_increase_button?: string | JsonUIElement | ArrayProperty,
    slider_steps?: string | JsonUIElement | ArrayProperty | Num,
    slider_direction?: string | JsonUIElement | ArrayProperty | Orientation,
    slider_timeout?: string | JsonUIElement | ArrayProperty | Num,
    slider_collection_name?: string | JsonUIElement | ArrayProperty,
    slider_name?: string | JsonUIElement | ArrayProperty,
    slider_select_on_hover?: string | JsonUIElement | ArrayProperty | Bool,
    slider_selected_button?: string | JsonUIElement | ArrayProperty,
    slider_deselected_button?: string | JsonUIElement | ArrayProperty,
    slider_box_control?: string | JsonUIElement | ArrayProperty,
    background_control?: string | JsonUIElement | ArrayProperty,
    background_hover_control?: string | JsonUIElement | ArrayProperty,
    progress_control?: string | JsonUIElement | ArrayProperty,
    progress_hover_control?: string | JsonUIElement | ArrayProperty,
    scrollbar_track_button?: string | JsonUIElement | ArrayProperty,
    scrollbar_touch_button?: string | JsonUIElement | ArrayProperty,
    scroll_speed?: string | JsonUIElement | ArrayProperty | Num,
    gesture_control_enabled?: string | JsonUIElement | ArrayProperty | Bool,
    always_handle_scrolling?: string | JsonUIElement | ArrayProperty | Bool,
    touch_mode?: string | JsonUIElement | ArrayProperty | Bool,
    scrollbar_box?: string | JsonUIElement | ArrayProperty,
    scrollbar_track?: string | JsonUIElement | ArrayProperty,
    scroll_view_port?: string | JsonUIElement | ArrayProperty,
    scroll_content?: string | JsonUIElement | ArrayProperty,
    scroll_box_and_track_panel?: string | JsonUIElement | ArrayProperty,
    jump_to_bottom_on_update?: string | JsonUIElement | ArrayProperty | Bool,
    renderer?: string | JsonUIElement | ArrayProperty | Renderer,
    gradient_direction?: string | JsonUIElement | ArrayProperty | Orientation,
    color1?: string | JsonUIElement | ArrayProperty | Vector4,
    color2?: string | JsonUIElement | ArrayProperty | Vector4,
    text_color?: string | JsonUIElement | ArrayProperty | Vector4,
    background_color?: string | JsonUIElement | ArrayProperty | Vector4,
    primary_color?: string | JsonUIElement | ArrayProperty | Vector4,
    secondary_color?: string | JsonUIElement | ArrayProperty | Vector4,
    camera_tilt_degrees?: string | JsonUIElement | ArrayProperty | Num,
    starting_rotation?: string | JsonUIElement | ArrayProperty | Num,
    use_selected_skin?: string | JsonUIElement | ArrayProperty | Bool,
    use_uuid?: string | JsonUIElement | ArrayProperty | Bool,
    use_skin_gui_scale?: string | JsonUIElement | ArrayProperty | Bool,
    use_player_paperdoll?: string | JsonUIElement | ArrayProperty | Bool,
    rotation?: string | JsonUIElement | ArrayProperty | RotationAuto,
    end_event?: string | JsonUIElement | ArrayProperty,
    render_only_when_topmost?: string | JsonUIElement | ArrayProperty | Bool,
    screen_not_flushable?: string | JsonUIElement | ArrayProperty | Bool,
    always_accepts_input?: string | JsonUIElement | ArrayProperty | Bool,
    render_game_behind?: string | JsonUIElement | ArrayProperty | Bool,
    absorbs_input?: string | JsonUIElement | ArrayProperty | Bool,
    is_showing_menu?: string | JsonUIElement | ArrayProperty | Bool,
    is_modal?: string | JsonUIElement | ArrayProperty | Bool,
    should_steal_mouse?: string | JsonUIElement | ArrayProperty | Bool,
    low_frequency_rendering?: string | JsonUIElement | ArrayProperty | Bool,
    screen_draws_last?: string | JsonUIElement | ArrayProperty | Bool,
    vr_mode?: string | JsonUIElement | ArrayProperty | Bool,
    force_render_below?: string | JsonUIElement | ArrayProperty | Bool,
    send_telemetry?: string | JsonUIElement | ArrayProperty | Bool,
    close_on_player_hurt?: string | JsonUIElement | ArrayProperty | Bool,
    cache_screen?: string | JsonUIElement | ArrayProperty | Bool,
    load_screen_immediately?: string | JsonUIElement | ArrayProperty | Bool,
    gamepad_cursor?: string | JsonUIElement | ArrayProperty | Bool,
    gamepad_cursor_deflection_mode?: string | JsonUIElement | ArrayProperty | Bool,
    should_be_skipped_during_automation?: string | JsonUIElement | ArrayProperty | Bool,
    inner_radius?: string | JsonUIElement | ArrayProperty | Num,
    outer_radius?: string | JsonUIElement | ArrayProperty | Num,
    state_controls?: string | JsonUIElement | ArrayProperty | ArrString,
    slice_count?: string | JsonUIElement | ArrayProperty | Num,
    button_name?: string | JsonUIElement | ArrayProperty,
    iterate_left_button_name?: string | JsonUIElement | ArrayProperty,
    iterate_right_button_name?: string | JsonUIElement | ArrayProperty,
    initial_button_slice?: string | JsonUIElement | ArrayProperty | Num,
    tts_name?: string | JsonUIElement | ArrayProperty,
    tts_control_header?: string | JsonUIElement | ArrayProperty,
    tts_section_header?: string | JsonUIElement | ArrayProperty,
    tts_control_type_order_priority?: string | JsonUIElement | ArrayProperty | Num,
    tts_index_priority?: string | JsonUIElement | ArrayProperty | Num,
    tts_toggle_on?: string | JsonUIElement | ArrayProperty,
    tts_toggle_off?: string | JsonUIElement | ArrayProperty,
    tts_override_control_value?: string | JsonUIElement | ArrayProperty,
    tts_inherit_siblings?: string | JsonUIElement | ArrayProperty | Bool,
    tts_value_changed?: string | JsonUIElement | ArrayProperty,
    ttsSectionContainer?: string | JsonUIElement | ArrayProperty | Bool,
    tts_ignore_count?: string | JsonUIElement | ArrayProperty | Bool,
    tts_skip_message?: string | JsonUIElement | ArrayProperty | Bool,
    tts_value_order_priority?: string | JsonUIElement | ArrayProperty | Num,
    tts_play_on_unchanged_focus_control?: string | JsonUIElement | ArrayProperty | Bool,
    tts_ignore_subsections?: string | JsonUIElement | ArrayProperty | Bool,
    text_tts?: string | JsonUIElement | ArrayProperty,
    use_priority?: string | JsonUIElement | ArrayProperty | Bool,
    priority?: string | JsonUIElement | ArrayProperty | Bool,
    width?: string | number,
    height?: string | number,
    x?: string | number,
    y?: string | number,
    [key: string]: string | JsonUIElement | ArrayProperty | any
}