import { JsonUIElement } from "../jsonUI/JsonUIElement"
import { Anchor } from "./Anchor"
import { ClipDirection } from "./ClipDirecion"
import { Collection } from "./Collection"
import { Direction } from "./Direction"
import { FocusContainerCustom } from "./FocusContainerCustom"
import { FocusNavigationMode } from "./FocusNavigationMode"
import { FontSize } from "./FontSize"
import { FontType } from "./FontType"
import { ArrayProperty } from "./LanguageInterface"
import { Orientation } from "./Orientation"
import { PropertyBagKey } from "./PropertyBagKeys"
import { Renderer } from "./Renderer"
import { RotationAuto } from "./RotationAuto"
import { SoundObject } from "./SoundObject"
import { TextType } from "./TextTypes"
import { TextureFileSystem } from "./TextureFileSystem"
import { Bool, Num, Vector2, Obj, Vector2_str, Vector3, ArrString, Vector4 } from "./Types"
import { Animation } from "../jsonUI/Animation"

type GlobalTypes = string | JsonUIElement | Animation;

export interface JsonUIProperty {
    visible?: GlobalTypes | ArrayProperty | Bool,
    enabled?: GlobalTypes | ArrayProperty | Bool,
    layer?: GlobalTypes | ArrayProperty | Num,
    alpha?: GlobalTypes | ArrayProperty | Num,
    propagate_alpha?: GlobalTypes | ArrayProperty | Bool,
    clips_children?: GlobalTypes | ArrayProperty | Bool,
    allow_clipping?: GlobalTypes | ArrayProperty | Bool,
    clip_offset?: GlobalTypes | ArrayProperty | Vector2,
    clip_state_change_event?: GlobalTypes | ArrayProperty,
    enable_scissor_test?: GlobalTypes | ArrayProperty | Bool,
    property_bag?: GlobalTypes | ArrayProperty | Obj | {
        [key in PropertyBagKey]: any
    },
    selected?: GlobalTypes | ArrayProperty | Bool,
    use_child_anchors?: GlobalTypes | ArrayProperty | Bool,
    disable_anim_fast_forward?: GlobalTypes | ArrayProperty | Bool,
    animation_reset_name?: GlobalTypes | ArrayProperty,
    ignored?: GlobalTypes | ArrayProperty | Bool,
    grid_position?: GlobalTypes | ArrayProperty | Vector2,
    collection_index?: GlobalTypes | ArrayProperty | Num,
    size?: GlobalTypes | ArrayProperty | Vector2_str,
    max_size?: GlobalTypes | ArrayProperty | Vector2_str,
    min_size?: GlobalTypes | ArrayProperty | Vector2_str,
    offset?: GlobalTypes | ArrayProperty | Vector2_str,
    anchor?: GlobalTypes | ArrayProperty | Anchor,
    anchor_from?: GlobalTypes | ArrayProperty | Anchor,
    anchor_to?: GlobalTypes | ArrayProperty | Anchor,
    inherit_max_sibling_width?: GlobalTypes | ArrayProperty | Bool,
    inherit_max_sibling_height?: GlobalTypes | ArrayProperty | Bool,
    use_anchored_offset?: GlobalTypes | ArrayProperty | Bool,
    contained?: GlobalTypes | ArrayProperty | Bool,
    draggable?: GlobalTypes | ArrayProperty | Direction,
    follows_cursor?: GlobalTypes | ArrayProperty | Bool,
    grid_dimensions?: GlobalTypes | ArrayProperty | Vector2,
    maximum_grid_items?: GlobalTypes | ArrayProperty | Num,
    grid_dimension_binding?: GlobalTypes | ArrayProperty,
    grid_rescaling_type?: GlobalTypes | ArrayProperty | Direction,
    grid_fill_direction?: GlobalTypes | ArrayProperty | Direction,
    grid_item_template?: GlobalTypes | ArrayProperty,
    precached_grid_item_count?: GlobalTypes | ArrayProperty | Num,
    text?: GlobalTypes | ArrayProperty,
    color?: GlobalTypes | ArrayProperty | Vector3,
    locked_color?: GlobalTypes | ArrayProperty | Vector3,
    shadow?: GlobalTypes | ArrayProperty | Bool,
    hide_hyphen?: GlobalTypes | ArrayProperty | Bool,
    notify_on_ellipses?: GlobalTypes | ArrayProperty | ArrString,
    enable_profanity_filter?: GlobalTypes | ArrayProperty | Bool,
    locked_alpha?: GlobalTypes | ArrayProperty | Num,
    font_scale_factor?: GlobalTypes | ArrayProperty | Num,
    localize?: GlobalTypes | ArrayProperty | Bool,
    line_padding?: GlobalTypes | ArrayProperty | Num,
    font_size?: GlobalTypes | ArrayProperty | FontSize,
    backup_font_type?: GlobalTypes | ArrayProperty | FontType,
    text_alignment?: GlobalTypes | ArrayProperty | Anchor,
    texture?: GlobalTypes | ArrayProperty,
    allow_debug_missing_texture?: GlobalTypes | ArrayProperty | Bool,
    uv?: GlobalTypes | ArrayProperty | Vector2,
    uv_size?: GlobalTypes | ArrayProperty | Vector2,
    texture_file_system?: GlobalTypes | ArrayProperty | TextureFileSystem,
    nineslice_size?: GlobalTypes | ArrayProperty | Vector2 | Vector4 | Num,
    tiled?: GlobalTypes | ArrayProperty | Bool | Vector2,
    tiled_scale?: GlobalTypes | ArrayProperty | Vector2,
    clip_direction?: GlobalTypes | ArrayProperty | ClipDirection,
    clip_ratio?: GlobalTypes | ArrayProperty | Num,
    clip_pixelperfect?: GlobalTypes | ArrayProperty | Bool,
    keep_ratio?: GlobalTypes | ArrayProperty | Bool,
    bilinear?: GlobalTypes | ArrayProperty | Bool,
    fill?: GlobalTypes | ArrayProperty | Bool,
    font_type?: GlobalTypes | ArrayProperty | FontType,
    "$fit_to_width"?: GlobalTypes | ArrayProperty | Bool,
    zip_folder?: GlobalTypes | ArrayProperty,
    grayscale?: GlobalTypes | ArrayProperty | Bool,
    force_texture_reload?: GlobalTypes | ArrayProperty | Bool,
    base_size?: GlobalTypes | ArrayProperty | Vector2,
    modal?: GlobalTypes | ArrayProperty | Bool,
    inline_modal?: GlobalTypes | ArrayProperty | Bool,
    always_listen_to_input?: GlobalTypes | ArrayProperty | Bool,
    always_handle_pointer?: GlobalTypes | ArrayProperty | Bool,
    always_handle_controller_direction?: GlobalTypes | ArrayProperty | Bool,
    hover_enabled?: GlobalTypes | ArrayProperty | Bool,
    prevent_touch_input?: GlobalTypes | ArrayProperty | Bool,
    consume_event?: GlobalTypes | ArrayProperty | Bool,
    consume_hover_events?: GlobalTypes | ArrayProperty | Bool,
    gesture_tracking_button?: GlobalTypes | ArrayProperty | Bool,
    default_focus_precedence?: GlobalTypes | ArrayProperty | Num,
    focus_enabled?: GlobalTypes | ArrayProperty | Bool,
    focus_wrap_enabled?: GlobalTypes | ArrayProperty | Bool,
    focus_magnet_enabled?: GlobalTypes | ArrayProperty | Bool,
    focus_identifier?: GlobalTypes | ArrayProperty,
    focus_change_down?: GlobalTypes | ArrayProperty,
    focus_change_up?: GlobalTypes | ArrayProperty,
    focus_change_left?: GlobalTypes | ArrayProperty,
    focus_change_right?: GlobalTypes | ArrayProperty,
    focus_mapping?: GlobalTypes | ArrayProperty | any[],
    focus_container?: GlobalTypes | ArrayProperty | Bool,
    use_last_focus?: GlobalTypes | ArrayProperty | Bool,
    focus_navigation_mode_left?: GlobalTypes | ArrayProperty | FocusNavigationMode,
    focus_navigation_mode_right?: GlobalTypes | ArrayProperty | FocusNavigationMode,
    focus_navigation_mode_down?: GlobalTypes | ArrayProperty | FocusNavigationMode,
    focus_navigation_mode_up?: GlobalTypes | ArrayProperty | FocusNavigationMode,
    focus_container_custom_left?: GlobalTypes | ArrayProperty | FocusContainerCustom[],
    focus_container_custom_right?: GlobalTypes | ArrayProperty | FocusContainerCustom[],
    focus_container_custom_down?: GlobalTypes | ArrayProperty | FocusContainerCustom[],
    focus_container_custom_up?: GlobalTypes | ArrayProperty | FocusContainerCustom[],
    default_control?: GlobalTypes | ArrayProperty,
    hover_control?: GlobalTypes | ArrayProperty,
    pressed_control?: GlobalTypes | ArrayProperty,
    locked_control?: GlobalTypes | ArrayProperty,
    radio_toggle_group?: GlobalTypes | ArrayProperty | Bool,
    toggle_name?: GlobalTypes | ArrayProperty,
    toggle_default_state?: GlobalTypes | ArrayProperty | Bool,
    toggle_group_forced_index?: GlobalTypes | ArrayProperty | Num,
    toggle_group_default_selected?: GlobalTypes | ArrayProperty | Num,
    reset_on_focus_lost?: GlobalTypes | ArrayProperty | Bool,
    toggle_on_hover?: GlobalTypes | ArrayProperty,
    toggle_on_button?: GlobalTypes | ArrayProperty,
    toggle_off_button?: GlobalTypes | ArrayProperty,
    enable_directional_toggling?: GlobalTypes | ArrayProperty | Bool,
    toggle_grid_collection_name?: GlobalTypes | ArrayProperty,
    unchecked_control?: GlobalTypes | ArrayProperty,
    checked_control?: GlobalTypes | ArrayProperty,
    unchecked_hover_control?: GlobalTypes | ArrayProperty
    checked_hover_control?: GlobalTypes | ArrayProperty
    unchecked_locked_control?: GlobalTypes | ArrayProperty,
    checked_locked_control?: GlobalTypes | ArrayProperty,
    unchecked_locked_hover_control?: GlobalTypes | ArrayProperty,
    checked_locked_hover_control?: GlobalTypes | ArrayProperty,
    dropdown_name?: GlobalTypes | ArrayProperty,
    dropdown_content_control?: GlobalTypes | ArrayProperty,
    dropdown_area?: GlobalTypes | ArrayProperty,
    sound_name?: GlobalTypes | ArrayProperty,
    sound_volume?: GlobalTypes | ArrayProperty | Num,
    sound_pitch?: GlobalTypes | ArrayProperty | Num,
    sounds?: GlobalTypes | ArrayProperty | SoundObject[],
    collection?: GlobalTypes | ArrayProperty | Collection,
    collection_name?: GlobalTypes | ArrayProperty | Collection,
    text_box_name?: GlobalTypes | ArrayProperty,
    text_edit_box_grid_collection_name?: GlobalTypes | ArrayProperty,
    constrain_to_rect?: GlobalTypes | ArrayProperty | Bool,
    enabled_newline?: GlobalTypes | ArrayProperty | Bool,
    text_type?: GlobalTypes | ArrayProperty | TextType,
    max_length?: GlobalTypes | ArrayProperty | Num,
    text_control?: GlobalTypes | ArrayProperty,
    place_holder_control?: GlobalTypes | ArrayProperty,
    can_be_deselected?: GlobalTypes | ArrayProperty | Bool,
    always_listening?: GlobalTypes | ArrayProperty | Bool,
    virtual_keyboard_buffer_control?: GlobalTypes | ArrayProperty,
    slider_track_button?: GlobalTypes | ArrayProperty,
    slider_small_decrease_button?: GlobalTypes | ArrayProperty,
    slider_small_increase_button?: GlobalTypes | ArrayProperty,
    slider_steps?: GlobalTypes | ArrayProperty | Num,
    slider_direction?: GlobalTypes | ArrayProperty | Orientation,
    slider_timeout?: GlobalTypes | ArrayProperty | Num,
    slider_collection_name?: GlobalTypes | ArrayProperty,
    slider_name?: GlobalTypes | ArrayProperty,
    slider_select_on_hover?: GlobalTypes | ArrayProperty | Bool,
    slider_selected_button?: GlobalTypes | ArrayProperty,
    slider_deselected_button?: GlobalTypes | ArrayProperty,
    slider_box_control?: GlobalTypes | ArrayProperty,
    background_control?: GlobalTypes | ArrayProperty,
    background_hover_control?: GlobalTypes | ArrayProperty,
    progress_control?: GlobalTypes | ArrayProperty,
    progress_hover_control?: GlobalTypes | ArrayProperty,
    scrollbar_track_button?: GlobalTypes | ArrayProperty,
    scrollbar_touch_button?: GlobalTypes | ArrayProperty,
    scroll_speed?: GlobalTypes | ArrayProperty | Num,
    gesture_control_enabled?: GlobalTypes | ArrayProperty | Bool,
    always_handle_scrolling?: GlobalTypes | ArrayProperty | Bool,
    touch_mode?: GlobalTypes | ArrayProperty | Bool,
    scrollbar_box?: GlobalTypes | ArrayProperty,
    scrollbar_track?: GlobalTypes | ArrayProperty,
    scroll_view_port?: GlobalTypes | ArrayProperty,
    scroll_content?: GlobalTypes | ArrayProperty,
    scroll_box_and_track_panel?: GlobalTypes | ArrayProperty,
    jump_to_bottom_on_update?: GlobalTypes | ArrayProperty | Bool,
    renderer?: GlobalTypes | ArrayProperty | Renderer,
    gradient_direction?: GlobalTypes | ArrayProperty | Orientation,
    color1?: GlobalTypes | ArrayProperty | Vector4,
    color2?: GlobalTypes | ArrayProperty | Vector4,
    text_color?: GlobalTypes | ArrayProperty | Vector4,
    background_color?: GlobalTypes | ArrayProperty | Vector4,
    primary_color?: GlobalTypes | ArrayProperty | Vector4,
    secondary_color?: GlobalTypes | ArrayProperty | Vector4,
    camera_tilt_degrees?: GlobalTypes | ArrayProperty | Num,
    starting_rotation?: GlobalTypes | ArrayProperty | Num,
    use_selected_skin?: GlobalTypes | ArrayProperty | Bool,
    use_uuid?: GlobalTypes | ArrayProperty | Bool,
    use_skin_gui_scale?: GlobalTypes | ArrayProperty | Bool,
    use_player_paperdoll?: GlobalTypes | ArrayProperty | Bool,
    rotation?: GlobalTypes | ArrayProperty | RotationAuto,
    end_event?: GlobalTypes | ArrayProperty,
    render_only_when_topmost?: GlobalTypes | ArrayProperty | Bool,
    screen_not_flushable?: GlobalTypes | ArrayProperty | Bool,
    always_accepts_input?: GlobalTypes | ArrayProperty | Bool,
    render_game_behind?: GlobalTypes | ArrayProperty | Bool,
    absorbs_input?: GlobalTypes | ArrayProperty | Bool,
    is_showing_menu?: GlobalTypes | ArrayProperty | Bool,
    is_modal?: GlobalTypes | ArrayProperty | Bool,
    should_steal_mouse?: GlobalTypes | ArrayProperty | Bool,
    low_frequency_rendering?: GlobalTypes | ArrayProperty | Bool,
    screen_draws_last?: GlobalTypes | ArrayProperty | Bool,
    vr_mode?: GlobalTypes | ArrayProperty | Bool,
    force_render_below?: GlobalTypes | ArrayProperty | Bool,
    send_telemetry?: GlobalTypes | ArrayProperty | Bool,
    close_on_player_hurt?: GlobalTypes | ArrayProperty | Bool,
    cache_screen?: GlobalTypes | ArrayProperty | Bool,
    load_screen_immediately?: GlobalTypes | ArrayProperty | Bool,
    gamepad_cursor?: GlobalTypes | ArrayProperty | Bool,
    gamepad_cursor_deflection_mode?: GlobalTypes | ArrayProperty | Bool,
    should_be_skipped_during_automation?: GlobalTypes | ArrayProperty | Bool,
    inner_radius?: GlobalTypes | ArrayProperty | Num,
    outer_radius?: GlobalTypes | ArrayProperty | Num,
    state_controls?: GlobalTypes | ArrayProperty | ArrString,
    slice_count?: GlobalTypes | ArrayProperty | Num,
    button_name?: GlobalTypes | ArrayProperty,
    iterate_left_button_name?: GlobalTypes | ArrayProperty,
    iterate_right_button_name?: GlobalTypes | ArrayProperty,
    initial_button_slice?: GlobalTypes | ArrayProperty | Num,
    tts_name?: GlobalTypes | ArrayProperty,
    tts_control_header?: GlobalTypes | ArrayProperty,
    tts_section_header?: GlobalTypes | ArrayProperty,
    tts_control_type_order_priority?: GlobalTypes | ArrayProperty | Num,
    tts_index_priority?: GlobalTypes | ArrayProperty | Num,
    tts_toggle_on?: GlobalTypes | ArrayProperty,
    tts_toggle_off?: GlobalTypes | ArrayProperty,
    tts_override_control_value?: GlobalTypes | ArrayProperty,
    tts_inherit_siblings?: GlobalTypes | ArrayProperty | Bool,
    tts_value_changed?: GlobalTypes | ArrayProperty,
    ttsSectionContainer?: GlobalTypes | ArrayProperty | Bool,
    tts_ignore_count?: GlobalTypes | ArrayProperty | Bool,
    tts_skip_message?: GlobalTypes | ArrayProperty | Bool,
    tts_value_order_priority?: GlobalTypes | ArrayProperty | Num,
    tts_play_on_unchanged_focus_control?: GlobalTypes | ArrayProperty | Bool,
    tts_ignore_subsections?: GlobalTypes | ArrayProperty | Bool,
    text_tts?: GlobalTypes | ArrayProperty,
    use_priority?: GlobalTypes | ArrayProperty | Bool,
    priority?: GlobalTypes | ArrayProperty | Bool,
    width?: string | number,
    height?: string | number,
    x?: string | number,
    y?: string | number,
    [key: string]: string | JsonUIElement | ArrayProperty | any
}