import { Types } from "../../enums/Types";
import { Properties } from "../properties/Properties";
import { Button } from "./Button";
import { CollectionPanel } from "./CollectionPanel";
import { Custom } from "./Custom";
import { Dropdown } from "./Dropdown";
import { EditBox } from "./EditBox";
import { Gird } from "./Gird";
import { Image } from "./Image";
import { InputPanel } from "./InputPanel";
import { Label } from "./Label";
import { Panel } from "./panel";
import { ScrollbarBox } from "./ScrollbarBox";
import { ScrollbarTrack } from "./ScrollbarTrack";
import { ScrollView } from "./ScrollView";
import { SelectionWheel } from "./SelectionWheel";
import { Slider } from "./Slider";
import { SliderBox } from "./SliderBox";
import { StackPanel } from "./StackPanel";
import { Toggle } from "./Toggle";

export type PropertiesType = {
    [Types.Panel]: Panel;
    [Types.StackPanel]: StackPanel;
    [Types.InputPanel]: InputPanel;
    [Types.CollectionPanel]: CollectionPanel;
    [Types.Button]: Button;
    [Types.Custom]: Custom;
    [Types.Dropdown]: Dropdown;
    [Types.EditBox]: EditBox;
    [Types.Grid]: Gird;
    [Types.Image]: Image;
    [Types.Label]: Label;
    [Types.Screen]: Screen;
    [Types.ScrollView]: ScrollView;
    [Types.ScrollbarBox]: ScrollbarBox;
    [Types.ScrollbarTrack]: ScrollbarTrack;
    [Types.SelectionWheel]: SelectionWheel;
    [Types.Slider]: Slider;
    [Types.SliderBox]: SliderBox;
    [Types.Toggle]: Toggle;
    [Types.Any]: Properties;
};
