import { JsonUIElement } from "./Element"
import { DefaultGlobalVariableTypes } from "./GlobalVariablesTypes"

export type JsonUIArrayName = "controls" | "bindings" | "button_mappings" | "variables";

export enum ElementTypes {
    Panel = "panel",
    StackPanel = "stack_panel",
    CollectionPanel = "collection_panel",
    InputPanel = "input_panel",
    Grid = "grid",
    Button = "button",
    Toggle = "toggle",
    Label = "label",
    Image = "image",
    Dropdown = "dropdown",
    Slider = "slider",
    SliderBox = "slider_box",
    EditBox = "edit_box",
    ScrollView = "scroll_view",
    ScrollbarTrack = "scrollbar_track",
    ScrollbarBox = "scrollbar_box",
    Factory = "factory",
    Screen = "screen",
    Custom = "custom",
    SelectionWheel = "selection_wheel"
}

export enum AnimTypes {
    Alpha = "alpha",
    Clip = "clip",
    Color = "color",
    FlipBook = "flip_book",
    Offset = "offset",
    Size = "size",
    Uv = "uv",
    Wait = "wait",
    AsepriteFlipBook = "aseprite_flip_book"
}

export enum Anchor {
    TopLeft = "top_left",
    TopMiddle = "top_middle",
    TopRight = "top_right",
    LeftMiddle = "left_middle",
    Center = "center",
    RightMiddle = "right_middle",
    BottomLeft = "bottom_left",
    BottomMiddle = "bottom_middle",
    BottomRight = "bottom_right"
}

export enum EasingTypes {
    Linear = "linear",
    Spring = "spring",
    InQuad = "in_quad",
    OutQuad = "out_quad",
    InOutQuad = "in_out_quad",
    InCuic = "in_cubic",
    OutCubic = "out_cubic",
    InOutCubic = "in_out_cubic",
    InQuart = "in_quart",
    OutQuart = "out_quart",
    InOutQuart = "in_out_quart",
    InQuint = "in_quint",
    OutQuint = "out_quint",
    InOutQuint = "in_out_quint",
    InSine = "in_sine",
    OutSine = "out_sine",
    InOutSine = "in_out_sine",
    InExpo = "in_expo",
    OutExpo = "out_expo",
    InOutExpo = "in_out_expo",
    InCirc = "in_circ",
    OutCirc = "out_circ",
    InOutCirc = "in_out_circ",
    InBounce = "in_bounce",
    OutBounce = "out_bounce",
    InOutBounce = "in_out_bounce",
    InBack = "in_back",
    OutBack = "out_back",
    InOutBack = "in_out_back",
    InElastic = "in_elastic",
    OutElastic = "out_elastic",
    InOutElastic = "in_out_elastic"
}

export interface AnimationData {
    duration: number | DefaultGlobalVariableTypes,
    destroy_at_end?: string | DefaultGlobalVariableTypes,
    easing?: EasingTypes,
    set_value: any | DefaultGlobalVariableTypes,
    override_from_value?: any,
    initial_uv?: [number, number],
    fps?: number,
    frame_count?: number,
    frame_step?: number,
    reversible?: boolean,
    resettable?: boolean,
    scale_from_starting_alpha?: boolean,
    activated?: boolean
}

export interface AnimationInterface {
    type: AnimTypes,
    name?: string,
    namespace?: string,
    start_value: any,
    loop?: boolean,
    play_event?: string,
    end_event?: string,
    start_event?: string,
    reset_event?: string,
    data: (AnimationData | number)[]
}

export interface ExtendInterface {
    name: string,
    namespace: string
}

export interface ElementInterface {
    type?: ElementTypes,
    name?: string,
    namespace?: string,
    extend?: JsonUIElement | ExtendInterface
}

export interface ElementCachedInterface {
    name?: string,
    namespace?: string,
    type?: string | ElementTypes,
    extend?: {
        name: string,
        namespace: string,
    }
}

export interface ElementVariables {
    require: string | boolean,
    value: any
}

export interface BindingInterface {
    ignored?: boolean | string,
    binding_type?: 'global' | 'view' | 'collection' | 'collection_details' | 'none',
    binding_name?: string,
    binding_name_override?: string,
    binding_collection_name?: string,
    binding_collection_prefix?: string,
    binding_condition?: 'always' | 'always_when_visible' | 'visible' | 'once' | 'none' | 'visibility_changed',
    source_control_name?: JsonUIElement | string,
    source_property_name?: string,
    target_property_name?: string,
    resolve_sibling_scope?: boolean | string
}

export interface ChildrenID {
    [key: string]: number
}

export interface RegisterResourcePack {
    version?: [number, number, number],
    uuid?: string,
    pack_name: string,
    description?: string,
    min_version?: [number, number, number]
}

export type Bool = boolean | string;
export type Num = number | string;
export type Vector2 = [number, number] | string;
export type Vector2_str = [number | string, number | string] | string;
export type Vector3 = [number, number, number] | string;
export type Vector4 = [number, number, number, number] | string;
export type ArrString = string[] | string;
export type Obj = Object | string;

export enum Renderer {
    HoverText = "hover_text_renderer",
    Structure3D = "3d_structure_renderer",
    SplashText = "splash_text_renderer",
    UIHoloCursor = "ui_holo_cursor",
    TrialTime = "trial_time_renderer",
    Panorama = "panorama_renderer",
    ActorPortrain = "actor_portrait_renderer",
    BannerPattern = "banner_pattern_renderer",
    LivePlayer = "live_player_renderer",
    WebView = "web_view_renderer",
    Hunger = "hunger_renderer",
    Bubbles = "bubbles_renderer",
    MobEffects = "mob_effects_renderer",
    Curson = "cursor_renderer",
    ProgressIndicator = "progress_indicator_renderer",
    Camera = "camera_renderer",
    HorseJump = "horse_jump_renderer",
    Armor = "armor_renderer",
    HorseHeart = "horse_heart_renderer",
    Heart = "heart_renderer",
    HotbarCooldown = "hotbar_cooldown_renderer",
    Hotbar = "hotbar_renderer",
    HudPlayer = "hud_player_renderer",
    LiveHorse = "live_horse_renderer",
    HolographucPost = "holographic_postrenderer",
    EnchantingBook = "enchanting_book_renderer",
    DebugScreen = "debug_screen_renderer",
    Gradient = "gradient_renderer",
    PaperDoll = "paper_doll_renderer",
    NameTag = "name_tag_renderer",
    FlyingItem = "flying_item_renderer",
    InventoryItem = "inventory_item_renderer",
    Credits = "credits_renderer",
    Vignette = "vignette_renderer",
    ProgressBar = "progress_bar_renderer",
    DebugOverlay = "debug_overlay_renderer",
    Background = "background_renderer",
    BohrModel = "bohr_model_renderer"
}

export enum RotationAuto {
    Auto = "auto",
    GestureX = "gesture_x",
    CustomY = "custom_y"
}

export enum TextType {
    ExtendedASCII = "ExtendedASCII",
    IdentifierChars = "IdentifierChars",
    NumberChars = "NumberChars"
}

export interface SoundObject {
    sound_name?: string,
    sound_volume?: Num,
    sound_pitch?: Num,
    min_seconds_between_plays?: Num,
}

export enum FocusNavigationMode {
    None = "none",
    Stop = "stop",
    Custom = "custom",
    Contained = "contained"
}

export interface FocusContainerCustom {
    other_focus_container_name?: string,
    focus_id_inside?: string
}

export enum ClipDirection {
    Left = "left",
    Right = "right",
    Up = "up",
    Down = "down",
    Center = "center"
}

export enum TextureFileSystem {
    InUserPackage = "InUserPackage",
    InAppPackage = "InAppPackage",
    RawPath = "RawPath",
    RawPersistent = "RawPersistent",
    InSettingsDir = "InSettingsDir",
    InExternalDir = "InExternalDir",
    InServerPackage = "InServerPackage",
    InDataDir = "InDataDir",
    InUserDir = "InUserDir",
    InWorldDir = "InWorldDir",
    StoreCache = "StoreCache"
}

export enum FontSize {
    Small = "small",
    Normal = "normal",
    Large = "large",
    ExtraLarge = "extra_large"
}

export enum FontType {
    Default = "default",
    Rune = "rune",
    Unicode = "unicode",
    Smooth = "smooth",
    MinecraftTen = "MinecraftTen"
}

export enum Orientation {
    Vertical = "vertical",
    Horizontal = "horizontal"
}

export enum Direction {
    Vertical = "vertical",
    Horizontal = "horizontal",
    Both = "both"
}

export interface JsonUIProperty {
    visible?: Bool,
    enabled?: Bool,
    layer?: Num,
    alpha?: Num,
    propagate_alpha?: Bool,
    clips_children?: Bool,
    allow_clipping?: Bool,
    clip_offset?: Vector2,
    clip_state_change_event?: string,
    enable_scissor_test?: Bool,
    property_bag?: Obj,
    selected?: Bool,
    use_child_anchors?: Bool,
    disable_anim_fast_forward?: Bool,
    animation_reset_name?: string,
    ignored?: Bool,
    grid_position?: Vector2,
    collection_index?: Num,
    size?: Vector2_str,
    max_size?: Vector2_str,
    min_size?: Vector2_str,
    offset?: Vector2_str,
    anchor_from?: Anchor,
    anchor_to?: Anchor,
    inherit_max_sibling_width?: Bool,
    inherit_max_sibling_height?: Bool,
    use_anchored_offset?: Bool,
    contained?: Bool,
    draggable?: Direction,
    follows_cursor?: Bool,
    grid_dimensions?: Vector2,
    maximum_grid_items?: Num,
    grid_dimension_binding?: string,
    grid_rescaling_type?: Direction,
    grid_fill_direction?: Direction,
    grid_item_template?: string,
    precached_grid_item_count?: Num,
    text?: string,
    color?: Vector3,
    locked_color?: Vector3,
    shadow?: Bool,
    hide_hyphen?: Bool,
    notify_on_ellipses?: ArrString,
    enable_profanity_filter?: Bool,
    locked_alpha?: Num,
    font_scale_factor?: Num,
    localize?: Bool,
    line_padding?: Num,
    font_size?: FontSize | string,
    backup_font_type?: FontType | string,
    text_alignment?: Anchor | string,
    texture?: string,
    allow_debug_missing_texture?: Bool,
    uv?: Vector2,
    uv_size?: Vector2,
    texture_file_system?: TextureFileSystem,
    nineslice_size?: Vector2 | Vector4 | Num,
    tiled?: Bool | Vector2,
    tiled_scale?: Vector2,
    clip_direction?: ClipDirection,
    clip_ratio?: Num,
    clip_pixelperfect?: Bool,
    keep_ratio?: Bool,
    bilinear?: Bool,
    fill?: Bool,
    "$fit_to_width"?: Bool,
    zip_folder?: string,
    grayscale?: Bool,
    force_texture_reload?: Bool,
    base_size?: Vector2,
    modal?: Bool,
    inline_modal?: Bool,
    always_listen_to_input?: Bool,
    always_handle_pointer?: Bool,
    always_handle_controller_direction?: Bool,
    hover_enabled?: Bool,
    prevent_touch_input?: Bool,
    consume_event?: Bool,
    consume_hover_events?: Bool,
    gesture_tracking_button?: Bool,
    default_focus_precedence?: Num,
    focus_enabled?: Bool,
    focus_wrap_enabled?: Bool,
    focus_magnet_enabled?: Bool,
    focus_identifier?: string,
    focus_change_down?: string,
    focus_change_up?: string,
    focus_change_left?: string,
    focus_change_right?: string,
    focus_mapping?: any[] | string,
    focus_container?: Bool,
    use_last_focus?: Bool,
    focus_navigation_mode_left?: FocusNavigationMode | string,
    focus_navigation_mode_right?: FocusNavigationMode | string,
    focus_navigation_mode_down?: FocusNavigationMode | string,
    focus_navigation_mode_up?: FocusNavigationMode | string,
    focus_container_custom_left?: FocusContainerCustom[] | string,
    focus_container_custom_right?: FocusContainerCustom[] | string,
    focus_container_custom_down?: FocusContainerCustom[] | string,
    focus_container_custom_up?: FocusContainerCustom[] | string,
    default_control?: string,
    hover_control?: string,
    pressed_control?: string,
    locked_control?: string,
    radio_toggle_group?: Bool,
    toggle_name?: string,
    toggle_default_state?: Bool,
    toggle_group_forced_index?: Num,
    toggle_group_default_selected?: Num,
    reset_on_focus_lost?: Bool,
    toggle_on_hover?: string,
    toggle_on_button?: string,
    toggle_off_button?: string,
    enable_directional_toggling?: Bool,
    toggle_grid_collection_name?: string,
    unchecked_control?: string,
    checked_control?: string,
    unchecked_hover_control?: string
    checked_hover_control?: string
    unchecked_locked_control?: string,
    checked_locked_control?: string,
    unchecked_locked_hover_control?: string,
    checked_locked_hover_control?: string,
    dropdown_name?: string,
    dropdown_content_control?: string,
    dropdown_area?: string,
    sound_name?: string,
    sound_volume?: Num,
    sound_pitch?: Num,
    sounds?: SoundObject[] | string,
    collection?: Collection | string,
    text_box_name?: string,
    text_edit_box_grid_collection_name?: string,
    constrain_to_rect?: Bool,
    enabled_newline?: Bool,
    text_type?: TextType,
    max_length?: Num,
    text_control?: string,
    place_holder_control?: string,
    can_be_deselected?: Bool,
    always_listening?: Bool,
    virtual_keyboard_buffer_control?: string,
    slider_track_button?: string,
    slider_small_decrease_button?: string,
    slider_small_increase_button?: string,
    slider_steps?: Num,
    slider_direction?: Orientation,
    slider_timeout?: Num,
    slider_collection_name?: string,
    slider_name?: string,
    slider_select_on_hover?: Bool,
    slider_selected_button?: string,
    slider_deselected_button?: string,
    slider_box_control?: string,
    background_control?: string,
    background_hover_control?: string,
    progress_control?: string,
    progress_hover_control?: string,
    scrollbar_track_button?: string,
    scrollbar_touch_button?: string,
    scroll_speed?: Num,
    gesture_control_enabled?: Bool,
    always_handle_scrolling?: Bool,
    touch_mode?: Bool,
    scrollbar_box?: string,
    scrollbar_track?: string,
    scroll_view_port?: string,
    scroll_content?: string,
    scroll_box_and_track_panel?: string,
    jump_to_bottom_on_update?: Bool,
    renderer?: Renderer | string,
    gradient_direction?: Orientation | string,
    color1?: Vector4,
    color2?: Vector4,
    text_color?: Vector4,
    background_color?: Vector4,
    primary_color?: Vector4,
    secondary_color?: Vector4,
    camera_tilt_degrees?: Num,
    starting_rotation?: Num,
    use_selected_skin?: Bool,
    use_uuid?: Bool,
    use_skin_gui_scale?: Bool,
    use_player_paperdoll?: Bool,
    rotation?: RotationAuto | string,
    end_event?: string,
    render_only_when_topmost?: Bool,
    screen_not_flushable?: Bool,
    always_accepts_input?: Bool,
    render_game_behind?: Bool,
    absorbs_input?: Bool,
    is_showing_menu?: Bool,
    is_modal?: Bool,
    should_steal_mouse?: Bool,
    low_frequency_rendering?: Bool,
    screen_draws_last?: Bool,
    vr_mode?: Bool,
    force_render_below?: Bool,
    send_telemetry?: Bool,
    close_on_player_hurt?: Bool,
    cache_screen?: Bool,
    load_screen_immediately?: Bool,
    gamepad_cursor?: Bool,
    gamepad_cursor_deflection_mode?: Bool,
    should_be_skipped_during_automation?: Bool,
    inner_radius?: Num,
    outer_radius?: Num,
    state_controls?: ArrString,
    slice_count?: Num,
    button_name?: string,
    iterate_left_button_name?: string,
    iterate_right_button_name?: string,
    initial_button_slice?: Num,
    tts_name?: string,
    tts_control_header?: string,
    tts_section_header?: string,
    tts_control_type_order_priority?: Num,
    tts_index_priority?: Num,
    tts_toggle_on?: string,
    tts_toggle_off?: string,
    tts_override_control_value?: string,
    tts_inherit_siblings?: Bool,
    tts_value_changed?: string,
    ttsSectionContainer?: Bool,
    tts_ignore_count?: Bool,
    tts_skip_message?: Bool,
    tts_value_order_priority?: Num,
    tts_play_on_unchanged_focus_control?: Bool,
    tts_ignore_subsections?: Bool,
    text_tts?: string,
    use_priority?: Bool,
    priority?: Bool,
    [key: string]: any
}

export interface ButtonMapping {
    ignored?: Bool,
    from_button_id?: FromKeybind | string,
    to_button_id?: ToKeybind | string,
    mapping_type?: MappingType | string,
    scope?: Scope | string,
    input_mode_condition?: InputModeCondition | string,
    ignore_input_scope?: Bool,
    consume_event?: Bool,
    handle_select?: Bool,
    handle_deselect?: Bool,
    button_up_right_of_first_refusal?: Bool
}

export enum MappingType {
    Global = "global",
    Pressed = "pressed",
    DoublePressed = "double_pressed",
    Focused = "forcused"
}

export enum Scope {
    View = "view",
    Controller = "controller"
}

export enum InputModeCondition {
    NotGaze = "not_gaze",
    NotGamepad = "not_gamepad",
    GamePadNadNotGaze = "gamepad_and_not_gaze"
}

export enum FromKeybind {
    MenuExit = "button.menu_exit",
    MenuCancel = "button.menu_cancel",
    MenuInventoryCancel = "button.menu_inventory_cancel ",
    MenuOk = "button.menu_ok",
    MenuSelect = "button.menu_select",
    ControllerSelect = "button.controller_select",
    MenuSecondarySelect = "button.menu_secondary_select",
    ControllerSecondarySelect = "button.controller_secondary_select",
    ControllerSecondarySelectLeft = "button.controller_secondary_select_left",
    ControllerSecondarySelectRight = "button.controller_secondary_select_right",
    ControllerStart = "button.controller_start",
    MenuUp = "button.menu_up",
    MenuDown = "button.menu_down",
    MenuLeft = "button.menu_left",
    MenuRight = "button.menu_right",
    MenuTabLeft = "button.menu_tab_left",
    MenuTabRight = "button.menu_tab_right",
    MenuAlternateTabLeft = "button.menu_alternate_tab_left",
    MenuAlternateTabRight = "button.menu_alternate_tab_right",
    MenuAutocomplete = "button.menu_autocomplete",
    MenuAutocompleteBack = "button.menu_autocomplete_back",
    ControllerAutocomplete = "button.controller_autocomplete",
    ControllerAutocompleteBack = "button.controller_autocomplete_back",
    MenuEditUp = "button.menu_textedit_up",
    MenuEditDown = "button.menu_textedit_down",
    ControllerEditUp = "button.controller_textedit_u",
    ControllerEditDown = "button.controller_textedit_down",
    MenuAutoPlace = "button.menu_auto_place",
    MenuInventoryDrop = "button.menu_inventory_drop",
    MenuInventoryDropAll = "button.menu_inventory_drop_all",
    MenuClear = "button.menu_clear",
    Chat = "button.chat",
    MobEffects = "button.mobeffects",
    keyEmote = "key.emote",
    Slot0 = "button.slot0",
    Slot1 = "button.slot1",
    Slot2 = "button.slot2",
    Slot3 = "button.slot3",
    Slot4 = "button.slot4",
    Slot5 = "button.slot5",
    Slot6 = "button.slot6",
    Slot7 = "button.slot7",
    Slot8 = "button.slot8",
    Slot9 = "button.slot9",
    InventoryRight = "button.inventory_right",
    InventoryLeft = "button.inventory_left",
    Scoreboard = "button.scoreboard",
    HideGui = "button.hide_gui",
    HideTooltips = "button.hide_tooltips",
    HidePaperdoll = "button.hide_paperdoll",
    MenuVRRealign = "button.menu_vr_realign"
}

export enum ToKeybind {
    OpenContentLogHistory = "button.open_content_log_history",
    ClearContentLogFiles = "button.clear_content_log_files",
    ClearMsaTokenButton = "button.clear_msa_token_button",
    TermsAndConditionsPopup = "button.terms_and_conditions_popup",
    Credits = "button.credits",
    UnlinkMsa = "button.unlink_msa",
    AttributePopup = "button.attribute_popup",
    LicensedContent = "button.licensed_content",
    FontLicense = "button.font_license",
    TosHyperlink = "button.tos_hyperlink",
    PrivpolHyperlink = "button.privpol_hyperlink",
    TosPopup = "button.tos_popup",
    PrivpolPopup = "button.privpol_popup",
    BindingButton = "button.binding_button",
    ResetBinding = "button.reset_binding",
    ResetKeyboardBindings = "button.reset_keyboard_bindings",
    ViewAccountErrors = "button.view_account_errors",
    PrevPage = "button.prev_page",
    NextPage = "button.next_page",
    BookExit = "button.book_exit",
    Send = "button.send",
    ChatAutocomplete = "button.chat_autocomplete",
    ChatAutocompleteBack = "button.chat_autocomplete_back",
    ChatPreviousMessage = "button.chat_previous_message",
    ChatNextMessage = "button.chat_next_message",
    commandBlockInputMinimize = "command_block.input_minimize",
    CommentOptionsClose = "button.comment_options_close",
    CommentFeedOptionsClose = "button.comment_feed_options_close",
    CloseComments = "button.close_comments",
    CommentNextButton = "button.comment_next_button",
    CommentPrevButton = "button.comment_prev_button",
    ShowSkip = "button.show_skip",
    RespawnButton = "button.respawn_button",
    MainMenuButton = "button.main_menu_button",
    RebindMode = "button.rebind_mode",
    DressingRoom = "button.dressing_room",
    EmoteSelected = "button.emote_selected",
    SelectEmoteSlot0 = "button.select_emote_slot_0",
    SelectEmoteSlot1 = "button.select_emote_slot_1",
    SelectEmoteSlot2 = "button.select_emote_slot_2",
    SelectEmoteSlot3 = "button.select_emote_slot_3",
    SelectEmoteSlot4 = "button.select_emote_slot_4",
    SelectEmoteSlot5 = "button.select_emote_slot_5",
    IterateSelectionLeft = "button.iterate_selection_left",
    IterateSelectionRight = "button.iterate_selection_right",
    FeedImage = "button.feed_image",
    NewPost = "button.newpost",
    AddScreenshot = "button.add_screenshot",
    FeedComment = "button.feed_comment",
    FeedPrevButton = "button.feed_prev_button",
    FeedNextButton = "button.feed_next_button",
    FeedNewPostClose = "button.feed_new_post_close",
    FeedOptionsClose = "button.feed_options_close",
    CloseFeed = "button.close_feed",
    ToProfileOrSkinsScreen = "button.to_profile_or_skins_screen",
    PlayerProfileCard = "button.player_profile_card",
    MenuContinue = "button.menu_continue",
    MenuServerStore = "button.menu_server_store",
    Screenshot = "button.screenshot",
    MenuHowToPlay = "button.menu_how_to_play",
    MenuPermission = "button.menu_permission",
    MenuInvitePlayers = "button.menu_invite_players",
    MenuQuit = "button.menu_quit",
    MenuFeed = "button.menu_feed",
    PauseFocusFiller = "button.pause_focus_filler",
    WakeUpButton = "button.wake_up_button",
    AddFriend = "button.add_friend",
    AddMember = "button.add_member",
    SendInvites = "button.send_invites",
    ManageFeedPrevButton = "button.manage_feed_prev_button",
    ManageFeedNextButton = "button.manage_feed_next_button",
    ManageFeedIgnore = "button.manage_feed_ignore",
    ManageFeedDelete = "button.manage_feed_delete",
    CloseManageFeed = "button.close_manage_feed",
    AnvilTakeAllPlaceAll = "button.anvil_take_all_place_all",
    AnvilCoalesceStack = "button.anvil_coalesce_stack",
    PlayButtonTarget = "$play_button_target", CartographyResultTakeAllPlaceAll = "button.cartography_result_take_all_place_all",
    Enchant = "button.enchant",
    GrindstoneTakeAllPlaceAll = "button.grindstone_take_all_place_all",
    GrindstoneCoalesceStack = "button.grindstone_coalesce_stack",
    LoomResultTakeAllPlaceAll = "button.loom_result_take_all_place_all",
    PatternSelect = "button.pattern_select",
    CycleRecipeLeft = "button.cycle_recipe_left",
    CycleRecipeRight = "button.cycle_recipe_right",
    TradeTakeAllPlaceAll = "button.trade_take_all_place_all",
    TradeTakeHalfPlaceOne = "button.trade_take_half_place_one",
    TradeCoalesceStack = "button.trade_coalesce_stack",
    MenuSignInToViewRealms = "button.menu_sign_in_to_view_realms",
    MenuRealmsWorldItemEdit = "button.menu_realms_world_item_edit",
    MenuRealmsFeed = "button.menu_realms_feed",
    MenuRealmsWorldItemRemove = "button.menu_realms_world_item_remove",
    MenuNetworkWorldItem = "button.menu_network_world_item",
    MenuNetworkServerWorldEdit = "button.menu_network_server_world_edit",
    ConnectToThirdPartyServer = "button.connect_to_third_party_server",
    ViewThirdPartyServerOffers = "button.view_third_party_server_offers",
    DescriptionReadToggle = "button.description_read_toggle",
    NewsReadToggle = "button.news_read_toggle",
    LocalWorldUpload = "button.local_world_upload",
    MenuStartLocalWorld = "button.menu_start_local_world",
    ConvertLegacyWorld = "button.convert_legacy_world",
    MenuLocalWorldItemEdit = "button.menu_local_world_item_edit",
    MenuLegacyWorldItemDelete = "button.menu_legacy_world_item_delete",
    ImportBetaRetailLocalWorld = "button.import_beta_retail_local_world",
    ImportBetaRetailLegacyWorld = "button.import_beta_retail_legacy_world",
    MenuNetworkAddFriend = "button.menu_network_add_friend",
    MenuNetworkJoinByCode = "button.menu_network_join_by_code",
    MenuQuickPlay = "button.menu_quick_play",
    NewWorldUpload = "button.new_world_upload",
    MenuLocalWorldCreate = "button.menu_local_world_create",
    CreateOnRealmsButton = "button.create_on_realms_button",
    ArchivedWorldUpload = "button.archived_world_upload",
    MenuImportLevel = "button.menu_import_level",
    MenuSyncLegacyWorlds = "button.menu_sync_legacy_worlds",
    RealmsWarningMoreInfo = "button.realms_warning_more_info",
    MenuRealmWorldTrial = "button.menu_realm_world_trial",
    MenuRealmNintendoFirstRealmPurchaseButton = "button.menu_realm_nintendo_first_realm_purchase_button",
    NoLocalWorldsLaunchHelp = "button.no_local_worlds_launch_help",
    MenuNetworkJoinByCodePopupJoin = "button.menu_network_join_by_code_popup_join",
    JoinServerAnyway = "button.join_server_anyway",
    CancelJoinServer = "button.cancel_join_server",
    TryMenuExit = "button.try_menu_exit",
    CloseDialog = "button.close_dialog",
    MenuPlay = "button.menu_play",
    MenuStore = "button.menu_store",
    MenuAchievements = "button.menu_achievements",
    MenuSettings = "button.menu_settings",
    Signin = "button.signin",
    MenuSkins = "button.menu_skins",
    ToProfileScreen = "button.to_profile_screen",
    MenuCourses = "button.menu_courses",
    MenuTutorial = "button.menu_tutorial",
    FeaturedWorld = "button.featured_world",
    SwitchAccounts = "button.switch_accounts",
    LaunchEditions = "button.launch_editions",
    EduFeedback = "button.edu_feedback",
    EduResources = "button.edu_resources",
    MenuBuyGame = "button.menu_buy_game",
    MenuInviteNotification = "button.menu_invite_notification",
    Search = "button.search",
    HotbarInventoryButton = "button.hotbar_inventory_button",
    SelectOffer = "button.select_offer",
    ActionButton = "button.action_button",
    CreateRealm = "button.create_realm",
    HotbarSelect = "button.hotbar_select",
    HotbarOk = "button.hotbar_ok",
    SlotPressed = "button.slot_pressed",
    HotbarInventoryLeft = "button.hotbar_inventory_left",
    HotbarInventoryRight = "button.hotbar_inventory_right",
    HideGuiAll = "button.hide_gui_all",
    HideTooltipsHud = "button.hide_tooltips_hud",
    HidePaperdollHud = "button.hide_paperdoll_hud",
    Slot1 = "button.slot_1",
    Slot2 = "button.slot_2",
    Slot3 = "button.slot_3",
    Slot4 = "button.slot_4",
    Slot5 = "button.slot_5",
    Slot6 = "button.slot_6",
    Slot7 = "button.slot_7",
    Slot8 = "button.slot_8",
    Slot9 = "button.slot_9",
    Slot0 = "button.slot_0",
    Chat = "button.chat",
    ViewSkin = "button.view_skin",
    DeleteAction = "button.delete_action",
    ExitStudent = "button.exit_student",
    PlayVideo = "button.play_video",
    MenuStoreError = "button.menu_store_error",
    LeftPanelTabIncrement = "button.left_panel_tab_increment",
    LeftPanelTabDecrement = "button.left_panel_tab_decrement",
    RightPanelTabIncrement = "button.right_panel_tab_increment",
    RightPanelTabDecrement = "button.right_panel_tab_decrement",
    LayoutIncrement = "button.layout_increment",
    LayoutDecrement = "button.layout_decrement",
    IsHovered = "button.is_hovered",
    ContainerTakeAllPlaceAll = "button.container_take_all_place_all",
    ContainerTakeHalfPlaceOne = "button.container_take_half_place_one",
    ContainerAutoPlace = "button.container_auto_place",
    CoalesceStack = "button.coalesce_stack",
    ShapeDrawing = "button.shape_drawing",
    DestroySelection = "button.destroy_selection",
    ClearSelectedRecipe = "button.clear_selected_recipe",
    ClearHotbarOrRemoveOne = "button.clear_hotbar_or_remove_one",
    ClearHotbarOrDrop = "button.clear_hotbar_or_drop",
    ContainerResetHeld = "button.container_reset_held",
    ContainerSlotHovered = "button.container_slot_hovered",
    ButtonHovered = "button.button_hovered",
    ShiftPaneFocus = "button.shift_pane_focus",
    FocusLeft = "button.focus_left",
    FocusRight = "button.focus_right",
    FilterToggleHovered = "button.filter_toggle_hovered",
    DropOne = "button.drop_one",
    CursorDropOne = "button.cursor_drop_one",
    DropAll = "button.drop_all",
    CursorDropAll = "button.cursor_drop_all",
    SearchBarClear = "button.search_bar_clear",
    SearchBarSelected = "button.search_bar_selected",
    SearchBarDeselected = "button.search_bar_deselected",
    MenuLeaveScreen = "button.menu_leave_screen",
    TurnDoll = "button.turn_doll",
    SelectSkin = "button.select_skin",
    SkinHovered = "button.skin_hovered",
    SkinUnhovered = "button.skin_unhovered",
    Leave = "button.leave",
    LeaveOnDevice = "button.leave_on_device",
    TextEditBoxSelected = "button.text_edit_box_selected",
    TextEditBoxDeselected = "button.text_edit_box_deselected",
    TextEditBoxHovered = "button.text_edit_box_hovered",
    TextEditBoxClear = "button.text_edit_box_clear",
    Help = "button.help",
    MenuOpenUri = "button.menu_open_uri",
    NoInteraction = "button.no_interaction",
    CopyToClipboard = "button.copy_to_clipboard",
    userConfirmDialogEscape = "user_confirm_dialog.escape",
    userConfirmDialogLeftButton = "user_confirm_dialog.left_button",
    userConfirmDialogMiddleButton = "user_confirm_dialog.middle_button",
    userConfirmDialogRightCancelButton = "user_confirm_dialog.rightcancel_button",
}

export enum Collection {
    BookPages = "book_pages",
    PickCollection = "pick_collection",
    OwnedList = "owned_list",
    UnownedList = "unowned_list",
    AutoComplete = "auto_complete",
    FontColors = "font_colors",
    HostMainCollection = "host_main_collection",
    PlayersCollection = "players_collection",
    HostTeleportCollection = "host_teleport_collection",
    HostTimeCollection = "host_time_collection",
    HostWeatherCollection = "host_weather_collection",
    RealmsCollection = "realms_collection",
    CoinPurchaseGrid = "coin_purchase_grid",
    CommentCollection = "comment_collection",
    ContentLogMessage = "content_log_message",
    WorldList = "world_list",
    RealmList = "realm_list",
    TemplatesCollection = "templates_collection",
    FeedCollection = "feed_collection",
    BossBars = "boss_bars",
    ChatTextGrid = "chat_text_grid",
    HotbarItems = "hotbar_items",
    ScoreboardPlayers = "scoreboard_players",
    ScoreboardScores = "scoreboard_scores",
    LeftHelperCollection = "left_helper_collection",
    RightHelperCollection = "right_helper_collection",
    OnlinePlatformFriends = "online_platform_friends",
    OnlineLinkedAccountFriends = "online_linked_account_friends",
    OnlineXboxLiveFriends = "online_xbox_live_friends",
    OfflinePlatformFriends = "offline_platform_friends",
    OfflineLinkedAccountFriends = "offline_linked_account_friends",
    OfflineXboxLiveFriends = "offline_xbox_live_friends",
    ManageFeedCollection = "manage_feed_collection",
    PackErrors = "pack_errors",
    MobEffectsCollection = "mob_effects_collection",
    FactoryCollection = "factory_collection",
    RatingsStarCollection = "ratings_star_collection",
    PermissionsCollection = "permissions_collection",
    ColorCollection = "color_collection",
    SkinPackInGridItem = "skin_pack_in_grid_item",
    PersonaFeaturedSkinPackCollection = "persona_featured_skin_pack_collection",
    BodySizeCollection = "body_size_collection",
    ArmSizeCollection = "arm_size_collection",
    CategoryFeaturedCollection = "category_featured_collection",
    MainFeaturedCollection = "main_featured_collection",
    ProfileFeaturedCollection = "profile_featured_collection",
    CustomSectionCollection = "custom_section_collection",
    FeaturedCollection = "featured_collection",
    FoobarCollection = "foobar_collection",
    EmoteCollection = "emote_collection",
    FriendsNetworkWorlds = "friends_network_worlds",
    CrossPlatformFriendsNetworkWorlds = "cross_platform_friends_network_worlds",
    LanNetworkWorlds = "lan_network_worlds",
    FriendsRealms = "friends_realms",
    ServersNetworkWorlds = "servers_network_worlds",
    ThirdPartyServerNetworkWorlds = "third_party_server_network_worlds",
    ServerScreenshotCollection = "server_screenshot_collection",
    ServerGamesCollection = "server_games_collection",
    LocalWorlds = "local_worlds",
    LegacyWorlds = "legacy_worlds",
    BetaRetailLocalWorlds = "beta_retail_local_worlds",
    PersonalRealms = "personal_realms",
    LoadingPersonalRealms = "loading_personal_realms",
    LoadingFriendsRealms = "loading_friends_realms",
    Photos = "photos",
    RequiredResourcepacks = "required_resourcepacks",
    OptionalResourcepacks = "optional_resourcepacks",
    PendingInvitesCollection = "pending_invites_collection",
    AdditionalRealmsSubscriptionsCollection = "additional_realms_subscriptions_collection",
    RealmsBranchCollection = "realms_branch_collection",
    RealmsBackupCollection = "realms_backup_collection",
    MembersCollection = "members_collection",
    InvitedFriendsCollection = "invited_friends_collection",
    UninvitedFriendsCollection = "uninvited_friends_collection",
    BlockedPlayersCollection = "blocked_players_collection",
    ScreenshotpickerCollection = "screenshotpicker_collection",
    CustomForm = "custom_form",
    FormButtons = "form_buttons",
    CustomDropdown = "custom_dropdown",
    KeyboardStandardCollection = "keyboard_standard_collection",
    KeyboardFullCollection = "keyboard_full_collection",
    GamepadCollection = "gamepad_collection",
    Languages = "languages",
    RealmsPlusSubscriptionsCollection = "realms_plus_subscriptions_collection",
    SelectedPackItemsGlobal = "#selected_pack_items_global",
    AvailablePackItemsGlobal = "#available_pack_items_global",
    RealmsPackItemsGlobal = "#realms_pack_items_global",
    UnownedPackItemsGlobal = "#unowned_pack_items_global",
    InvalidPackItemsGlobal = "#invalid_pack_items_global",
    SelectedPackItemsLevel = "#selected_pack_items_level",
    AvailablePackItemsLevel = "#available_pack_items_level",
    RealmsPackItemsLevel = "#realms_pack_items_level",
    UnownedPackItemsLevel = "#unowned_pack_items_level",
    InvalidPackItemsLevel = "#invalid_pack_items_level",
    SelectedPackItemsAddon = "#selected_pack_items_addon",
    AvailablePackItemsAddon = "#available_pack_items_addon",
    RealmsPackItemsAddon = "#realms_pack_items_addon",
    UnownedPackItemsAddon = "#unowned_pack_items_addon",
    InvalidPackItemsAddon = "#invalid_pack_items_addon",
    ExperimentalToggles = "experimental_toggles",
    WorldPanel = "world_panel",
    WorldTemplatePanel = "world_template_panel",
    ResourcePanel = "resource_panel",
    BehaviorPanel = "behavior_panel",
    SkinPanel = "skin_panel",
    CachePanel = "cache_panel",
    DependentPacksPanel = "dependent_packs_panel",
    DependencyPanel = "dependency_panel",
    SaveSizeGrid = "save_size_grid",
    SaveOffsetGrid = "save_offset_grid",
    LoadOffsetGrid = "load_offset_grid",
    ExportSizeGrid = "export_size_grid",
    ExportOffsetGrid = "export_offset_grid",
    UgcItems = "ugc_items",
    WorldTemplates = "world_templates",
    RealmsPlusTemplates = "realms_plus_templates",
    CustomWorldTemplates = "custom_world_templates",
    SuggestedOffersCollection = "#suggested_offers_collection",
    AnvilInputItems = "anvil_input_items",
    AnvilMaterialItems = "anvil_material_items",
    AnvilResultItems = "anvil_result_items",
    BeaconPaymentItems = "beacon_payment_items",
    Speed = "speed",
    Haste = "haste",
    Resist = "resist",
    Jump = "jump",
    Strength = "strength",
    Regen = "regen",
    Extra = "extra",
    Confirm = "confirm",
    Cancel = "cancel",
    BrewingFuelItem = "brewing_fuel_item",
    BrewingInputItem = "brewing_input_item",
    BrewingResultItems = "brewing_result_items",
    CartographyInputItems = "cartography_input_items",
    CartographyAdditionalItems = "cartography_additional_items",
    CartographyResultItems = "cartography_result_items",
    EnchantingInputItems = "enchanting_input_items",
    EnchantingLapisItems = "enchanting_lapis_items",
    EnchantButtons = "#enchant_buttons",
    FurnaceIngredientItems = "furnace_ingredient_items",
    FurnaceFuelItems = "furnace_fuel_items",
    FurnaceOutputItems = "furnace_output_items",
    GrindstoneInputItems = "grindstone_input_items",
    GrindstoneAdditionalItems = "grindstone_additional_items",
    GrindstoneResultItems = "grindstone_result_items",
    HorseEquipItems = "horse_equip_items",
    ArmorItems = "armor_items",
    OffhandItems = "offhand_items",
    CraftingInputItems = "crafting_input_items",
    CraftingOutputItems = "crafting_output_items",
    RecipeBook = "recipe_book",
    LoomInputItems = "loom_input_items",
    LoomDyeItems = "loom_dye_items",
    LoomMaterialItems = "loom_material_items",
    LoomResultItems = "loom_result_items",
    Patterns = "patterns",
    SmithingTableInputItems = "smithing_table_input_items",
    SmithingTableMaterialItems = "smithing_table_material_items",
    SmithingTableResultItems = "smithing_table_result_items",
    StonecutterInputItems = "stonecutter_input_items",
    StonecutterResultItems = "stonecutter_result_items",
    Stones = "stones",
    Trade2Ingredient1Item = "trade2_ingredient1_item",
    Trade2Ingredient2Item = "trade2_ingredient2_item",
    Trade2ResultItem = "trade2_result_item",
    TradeItem1 = "trade_item_1",
    TradeItem2 = "trade_item_2",
    SellItem = "sell_item",
    Trades = "trades",
    TradeTiers = "trade_tiers",
}

export type ModifyObjectType = string | JsonUIElement | BindingInterface;