export enum Types {
    Panel = "panel",
    StackPanel = "stack_panel",
    CollectionPanel = "collection_panel",
    InputPanel = "input_panel",
    Grid = "grid",
    Button = "button",
    Toggle = "toggle",
    Label = "label",
    Image = "image",
    Dropdown = "dropdown",
    Slider = "slider",
    SliderBox = "slider_box",
    EditBox = "edit_box",
    ScrollView = "scroll_view",
    ScrollbarTrack = "scrollbar_track",
    ScrollbarBox = "scrollbar_box",
    Screen = "screen",
    Custom = "custom",
    SelectionWheel = "selection_wheel",
    Factory = "Any",
    LabelCycler = "Any",
    ImageCycler = "Any",
    GridPageIndicator = "Any",
    CarouselLabel = "Any",
    ScrollTrack = "Any",
    Any = "Any",
}
